// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6HWwGIevdCbOVxkL8Dpuvh84YnlaXjQQ',
    appId: '1:328171646651:web:868e6408d19fc9740b839e',
    messagingSenderId: '328171646651',
    projectId: 'trackereyeseeu',
    authDomain: 'trackereyeseeu.firebaseapp.com',
    storageBucket: 'trackereyeseeu.firebasestorage.app',
    measurementId: 'G-35KPN93W4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAguyq4b_m21Bov3mUzOsxPHCU6DHIVVsQ',
    appId: '1:328171646651:android:a488c84960d022850b839e',
    messagingSenderId: '328171646651',
    projectId: 'trackereyeseeu',
    storageBucket: 'trackereyeseeu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1hcUZpO51VIAO2pQNWPYWpuy9L3eB9hQ',
    appId: '1:328171646651:ios:2b84220263fe03180b839e',
    messagingSenderId: '328171646651',
    projectId: 'trackereyeseeu',
    storageBucket: 'trackereyeseeu.firebasestorage.app',
    iosBundleId: 'com.example.eyeSeeu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1hcUZpO51VIAO2pQNWPYWpuy9L3eB9hQ',
    appId: '1:328171646651:ios:2b84220263fe03180b839e',
    messagingSenderId: '328171646651',
    projectId: 'trackereyeseeu',
    storageBucket: 'trackereyeseeu.firebasestorage.app',
    iosBundleId: 'com.example.eyeSeeu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6HWwGIevdCbOVxkL8Dpuvh84YnlaXjQQ',
    appId: '1:328171646651:web:46c740d155f3f8b90b839e',
    messagingSenderId: '328171646651',
    projectId: 'trackereyeseeu',
    authDomain: 'trackereyeseeu.firebaseapp.com',
    storageBucket: 'trackereyeseeu.firebasestorage.app',
    measurementId: 'G-55Y4EM6N47',
  );

}